name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  Project_name: Petclinic

jobs:
  checking_pipeline_env: 
    runs-on: self-hosted
    env:
      Greeting: Hello

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: "$Greeting my petclinic project"
      run: echo "My first $Project_name"
      # run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
  checking_job_env:
    runs-on: self-hosted
    steps:
    - name: testing the variables
      run: echo "looking for first job variable $Greeting and $Project_name"
  checking_secret_variable:
    runs-on: self-hosted
    steps:
    - name: testing the variables
      run: echo "my designation is $field"