name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  Project_name: Petclinic

jobs:
  build: 
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: "Hello my petclinic project"
      run: echo "My first $Project_name"
      # run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"

    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'  # Specify your Java version here
    #     distribution: 'adoptopenjdk'

    # - name: Package with maven
    #   run: ./mvnw package
    # - name: Hosting the website
    #   run: java -jar target/*.jar